server:
  port: 10010
jwt:
  issuer: issuerJwt
  secret: secretJwt
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://link-jub-jub.cvicqtodruxp.ap-northeast-2.rds.amazonaws.com:3306/linkjub_local
    username: admin
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100  #컬렉션 데이터 쿼리 where 절에 in query 100번 실행 한다. (1:N:M -> 1:1:1)
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
#    com.depromeet.articlereminder: debug
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
