server:
  port: 9090
jwt:
  issuer: issuerJwt
  secret: secretJwt
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://link-jub-jub.cvicqtodruxp.ap-northeast-2.rds.amazonaws.com:3306/linkjub_dev
    username: admin
    password: 12fldwnq!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100  #컬렉션 데이터 쿼리 where 절에 in query 100번 실행 한다. (1:N:M -> 1:1:1)
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: info
    com.depromeet.articlereminder: debug
  file:
    name: dev_log
    path: /home/ec2-user/dev/logs


